/**
 * Sample consumer script for image generation via
 * @pmark/arcadia/intelligence/client.
 *
 * Same shape as consumer-example.ts, but with `capability: "image.generate"`.
 * This example uses the local ComfyUI image route. Enable it with
 * `ARCADIA_COMFYUI_IMAGE_ROUTE=comfyui` before starting the service.
 * Cloud image generation is still available by using
 * `execution: "cloud-required"` and `executionPolicy.allowPaidUsage: true`
 * with `ARCADIA_LITELLM_CLOUD_IMAGE_ROUTE` configured. The job result is
 * never a provider URL or inline base64 — Arcadia downloads or decodes the
 * generated bytes itself, hashes and stores them under the workspace's
 * artifacts directory, and returns a durable artifact-reference manifest
 * instead. This script submits an image request, waits for it, and
 * downloads the resulting bytes through the artifact reference.
 *
 * Run the real service first, with the local ComfyUI image route enabled:
 *   ARCADIA_COMFYUI_IMAGE_ROUTE=comfyui \
 *     pnpm arcadia intelligence serve --workspace ./tmp/demo-workspace --port 4710
 *
 * Then run this script against it (after `pnpm link --global @pmark/arcadia`
 * in the consumer repo):
 *   tsx docs/intelligence/examples/image-generation-example.ts
 */
import { writeFile } from "node:fs/promises";
import { ArcadiaIntelligenceClient } from "@pmark/arcadia/intelligence/client";
import type {
  ExecutionPolicy,
  IntelligenceImageGenerationResult,
  IntelligenceJob,
  IntelligenceRequest,
  OutputContract,
  PromptTemplateRef,
} from "@pmark/arcadia/intelligence/contracts";

// 1. Configure the client. The base URL is owned by the consumer app's own
//    config/env, not by the linked package.
const client = new ArcadiaIntelligenceClient({
  baseUrl: process.env.ARCADIA_INTELLIGENCE_BASE_URL ?? "http://127.0.0.1:4710",
});

// 2. Describe the shape of the result you want back. For "image.generate",
//    Arcadia's manifest shape is `{ artifacts: [...], generation?: {...} }`
//    (see IntelligenceImageGenerationResult) — write your schema against
//    that, requiring only the fields you care about.
const outputContract: OutputContract = {
  schemaId: "example-app.generated-image.v1",
  schemaVersion: 1,
  jsonSchema: {
    type: "object",
    properties: {
      artifacts: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          properties: {
            id: { type: "string" },
            kind: { type: "string", const: "image" },
            uri: { type: "string" },
            mimeType: { type: "string" },
            sha256: { type: "string" },
            byteSize: { type: "number" },
            dimensions: {
              type: "object",
              properties: { width: { type: "number" }, height: { type: "number" } },
            },
          },
          required: ["id", "kind", "uri", "mimeType", "sha256", "byteSize"],
        },
      },
    },
    required: ["artifacts"],
  },
};

// 3. Reference the prompt template you used to build this request.
const template: PromptTemplateRef = {
  id: "example-app.image-prompt-template",
  version: "1",
  sourceRef: "example-app/src/prompts/generatedImage.md",
};

// 4. Local image generation does not require paid-usage authorization.
const executionPolicy: ExecutionPolicy = {
  allowPaidUsage: false,
  maxRetries: 1,
};

// 5. Build the request. `capability: "image.generate"` plus
//    `execution: "local-required"` routes this to the configured local
//    Codex image route (only the "quality" profile is supported for
//    image generation today). `input.prompt` is required for this
//    capability; `input.n` is optional.
//    `requirements.imageSize`/`requirements.transparency` are validated —
//    Arcadia rejects unsupported values instead of silently ignoring them.
const request: IntelligenceRequest = {
  idempotencyKey: `example-app-generated-image-${Date.now()}`,
  operationId: "example-app.generate-illustration",
  clientApp: "example-app",
  projectId: "proj_example",
  capability: "image.generate",
  execution: "local-required",
  profile: "quality",
  input: {
    prompt: "a watercolor illustration of a lighthouse at sunrise",
    n: 1,
  },
  requirements: {
    imageSize: "1024x1024",
    transparency: false,
  },
  outputContract,
  template,
  executionPolicy,
};

async function main() {
  // 6. Submit. `created` is false if this idempotencyKey already exists.
  const { job: submittedJob, created } = await client.submit(request);
  console.log(`submitted job ${submittedJob.id} (created=${created})`);

  // 7. Let the client poll until the job reaches a terminal status
  //    (completed, failed, or blocked). Image generation can take longer
  //    than text, so give it a longer timeout than the text example.
  let job: IntelligenceJob = await client.waitForCompletion(submittedJob.id, {
    pollIntervalMs: 1_000,
    timeoutMs: 120_000,
  });

  // 8. A failed/blocked job can be retried once (subject to maxRetries).
  //    Blocked commonly means ARCADIA_LITELLM_CLOUD_IMAGE_ROUTE isn't
  //    configured (error.code "ROUTE_NOT_CONFIGURED").
  if (job.status === "failed" || job.status === "blocked") {
    console.log(`job ${job.id} ${job.status}, retrying once`);
    const { job: retriedJob } = await client.retry(job.id);
    job = await client.waitForCompletion(retriedJob.id, { timeoutMs: 120_000 });
  }

  // 9. Read the outcome and download each artifact's bytes through its
  //    stable reference — never from a provider URL.
  switch (job.status) {
    case "completed": {
      const result = job.result as unknown as IntelligenceImageGenerationResult;
      console.log(`generated ${result.artifacts.length} image artifact(s)`);

      for (const artifact of result.artifacts) {
        const { bytes, contentType } = await client.getArtifact(artifact.uri);
        const extension = contentType.split("/")[1] ?? "bin";
        const localPath = `./tmp/${artifact.id}.${extension}`;
        await writeFile(localPath, Buffer.from(bytes));
        console.log(
          `saved ${artifact.id} (${artifact.mimeType}, ${artifact.byteSize} bytes, ` +
            `sha256 ${artifact.sha256}) -> ${localPath}`,
        );
      }
      console.log("usage:", job.usage);
      console.log("validation:", job.validation);
      break;
    }
    case "failed":
      console.error("job failed:", job.error);
      break;
    case "blocked":
      console.error("job blocked (e.g. no image route configured):", job.error);
      break;
    default:
      console.error(`unexpected terminal status: ${job.status}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
