import { describe, expect, it } from "vitest";
import { buildFlightDeck } from "./flight-deck";
import type { DashboardSnapshot } from "./types";
import type { WorkQueue } from "./work-queue-types";

const queue = (): WorkQueue => ({ generatedAt: "", revision: 1, nextActionKey: null, unpositionedCount: 0, orderValid: true, undoReceipt: null, counts: { ready: 1, running: 0, flagged: 0, attention: 0 }, ordered: [{ id: "a", state: "ready", attentionKind: null, selected: true, projectId: "p", projectName: "Arcadia", projectSlug: "arcadia", planSlug: "deck", actionId: "build", actionTitle: "Build board", responsibility: "agent", expectedArtifact: null, tokenImpact: null, tokenBudget: null, milestone: "Flight", status: "open", reason: "", nextAction: "Build it", blockers: [], runId: null, decisionId: null, updatedAt: "" }] });
const snapshot = (): DashboardSnapshot => ({ generatedAt: "", workspace: "", counts: {} as DashboardSnapshot["counts"], dailyAdvantage: null, reviewFocus: null, agentQueue: {} as DashboardSnapshot["agentQueue"], projects: [], attentionItems: [], activityEvents: [], capabilities: [], blogging: {} as DashboardSnapshot["blogging"], rebuster: {} as DashboardSnapshot["rebuster"], currentMilestones: [], backBurnerItems: [], recentRuns: [{ id: "r", status: "failed", statusLabel: "Failed", projectId: "p", projectName: "Arcadia", startedAt: "", updatedAt: "", completedAt: null, workItemTitle: "", actionTitle: "Build board", summary: "", planSummary: "", currentStep: null, latestMessage: "failed", artifactsProduced: [], failureReason: "bad", reviewReason: null, missionLogPath: null }], recentArtifacts: [{ id: "x", title: "Evidence", artifactType: "report", status: "ready", statusLabel: "Ready", path: "proof.md", projectId: "p", projectName: "Arcadia", workItemTitle: null, actionTitle: "Build board", updatedAt: "" }], requiresReviewItems: [{ id: "structural", slug: "", decisionId: "", decisionSlug: "", displayId: "", workItemId: null, actionId: "build", projectId: "p", project: "Arcadia", goal: null, outcome: null, status: "", statusLabel: "", category: "decision", decisionNeeded: "Choose", context: "", recommendation: null, proposedAction: "", missingFields: [], options: [], sourceInput: "", createdAt: "", updatedAt: "", resultingAskRequestId: null, contextJson: null, resolvedIntent: "ActionClarification", packetArtifactId: null, codexInvocationId: null, artifactPath: null, promptPath: null, finalMessagePath: null, validationPath: null, planningArtifact: null }, { id: "loose", slug: "", decisionId: "", decisionSlug: "", displayId: "", workItemId: null, actionId: null, projectId: "p", project: "Arcadia", goal: null, outcome: null, status: "", statusLabel: "", category: "decision", decisionNeeded: "Loose", context: "", recommendation: null, proposedAction: "", missingFields: [], options: [], sourceInput: "", createdAt: "", updatedAt: "", resultingAskRequestId: null, contextJson: null, resolvedIntent: "ActionClarification", packetArtifactId: null, codexInvocationId: null, artifactPath: null, promptPath: null, finalMessagePath: null, validationPath: null, planningArtifact: null }] });

describe("buildFlightDeck", () => it("places each entity once and keeps unlinked Decisions in an unattached lane", () => { const lanes = buildFlightDeck(queue(), snapshot()); const cards = lanes.flatMap((lane) => lane.cards); expect(cards.map((card) => card.id)).toEqual(["action:build", "decision:structural", "run:r", "artifact:x", "decision:loose"]); expect(cards.find((card) => card.id === "run:r")?.column).toBe("needs-you"); expect(lanes.find((lane) => lane.planSlug === null)?.cards[0]?.relation).toBe("unattached"); }));

it("uses a named Plan only as a prose link and puts QA Decisions in Proving", () => {
  const data = snapshot();
  data.requiresReviewItems[1] = { ...data.requiresReviewItems[1]!, context: "Review deck evidence", category: "qa" };
  const card = buildFlightDeck(queue(), data).flatMap((lane) => lane.cards).find((item) => item.id === "decision:loose");
  expect(card).toMatchObject({ planSlug: "deck", relation: "named-in-prose", column: "proving" });
});
