import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type Database from "better-sqlite3";
import { createId } from "../../utils/id.js";
import { nowIso } from "../../utils/time.js";
import { getWorkspacePaths } from "../../workspace/paths.js";
import type { IntelligenceArtifactRecord, JsonValue } from "../types.js";
import { mimeTypeToExtension, parseImageDimensions, sniffImageMimeType } from "./imageMeta.js";

interface IntelligenceJobArtifactRow {
  id: string;
  job_id: string;
  kind: string;
  mime_type: string;
  byte_size: number;
  sha256: string;
  width: number | null;
  height: number | null;
  relative_path: string;
  metadata_json: string;
  created_at: string;
}

/**
 * Durable local storage for binary artifacts generated by Intelligence jobs
 * (currently images). Bytes are written under the workspace's existing
 * `artifacts/` directory; metadata (hash, size, dimensions, mime type) is
 * tracked in `intelligence_job_artifacts`. Job results never carry raw
 * bytes or provider URLs — only the IntelligenceArtifactRecord this returns.
 */
export interface IntelligenceArtifactStore {
  saveImageBytes(input: {
    jobId: string;
    bytes: Buffer;
    metadata?: JsonValue;
  }): Promise<IntelligenceArtifactRecord>;

  getArtifactBytes(
    artifactId: string,
  ): Promise<{ bytes: Buffer; mimeType: string } | undefined>;
}

export function createSqliteIntelligenceArtifactStore(
  db: Database.Database,
  workspaceRoot: string,
): IntelligenceArtifactStore {
  const artifactsDir = getWorkspacePaths(workspaceRoot).artifacts;

  async function saveImageBytes(input: {
    jobId: string;
    bytes: Buffer;
    metadata?: JsonValue;
  }): Promise<IntelligenceArtifactRecord> {
    const mimeType = sniffImageMimeType(input.bytes);
    const dimensions = parseImageDimensions(input.bytes);
    const id = createId("intelligenceArtifact");
    const fileName = `${id}.${mimeTypeToExtension(mimeType)}`;
    const relativePath = ["intelligence", input.jobId, fileName].join("/");
    const absolutePath = path.join(artifactsDir, relativePath);

    mkdirSync(path.dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, input.bytes);

    const sha256 = createHash("sha256").update(input.bytes).digest("hex");

    db.prepare(
      `INSERT INTO intelligence_job_artifacts (
        id, job_id, kind, mime_type, byte_size, sha256, width, height,
        relative_path, metadata_json, created_at
      ) VALUES (?, ?, 'image', ?, ?, ?, ?, ?, ?, ?, ?)`,
    ).run(
      id,
      input.jobId,
      mimeType,
      input.bytes.byteLength,
      sha256,
      dimensions?.width ?? null,
      dimensions?.height ?? null,
      relativePath,
      JSON.stringify(input.metadata ?? {}),
      nowIso(),
    );

    return {
      id,
      kind: "image",
      uri: `/api/intelligence/artifacts/${id}`,
      mimeType,
      sha256,
      byteSize: input.bytes.byteLength,
      dimensions,
      metadata: input.metadata,
    };
  }

  async function getArtifactBytes(
    artifactId: string,
  ): Promise<{ bytes: Buffer; mimeType: string } | undefined> {
    const row = db
      .prepare("SELECT * FROM intelligence_job_artifacts WHERE id = ?")
      .get(artifactId) as IntelligenceJobArtifactRow | undefined;
    if (!row) {
      return undefined;
    }

    const absolutePath = path.join(artifactsDir, row.relative_path);
    return { bytes: readFileSync(absolutePath), mimeType: row.mime_type };
  }

  return { saveImageBytes, getArtifactBytes };
}
